services:
  db:
    image: mysql:8.0
    container_name: mysql_sistema_escolar
    restart: always
    environment:
      MYSQL_DATABASE: sistema_escolar
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede_escolar
  app:
    image: glaudencio123/sistema-escolar-simples:v1
    container_name: sistema_escolar_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - rede_escolar
volumes:
  db_data:
networks:
  rede_escolar:
