services:
  db:
    image: mysql:8.0
    container_name: mysql_sistema_escolar
    restart: always
    environment:
      MYSQL_DATABASE: sistema_escolar
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede_escolar
  app:
    image: glaudencio123/sistema-escolar-simples:v1
    container_name: sistema_escolar_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sistema_escolar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha123
    networks:
      - rede_escolar
volumes:
  db_data:
networks:
  rede_escolar:
